# Copyright (c) 2022-2023, PostgreSQL Global Development Group

tests += {
  'name': 'test_misc',
  'sd': meson.current_source_dir(),
  'bd': meson.current_build_dir(),
  'tap': {
    'tests': [
      't/001_constraint_validation.pl',
      't/002_tablespace.pl',
      't/003_check_guc.pl',
      't/004_io_direct.pl',
      't/016_index_vacuum_time.pl',
      't/017_vacuum_failsafe.pl',
      't/018_vacuum_interrupts.pl',
      't/019_resqueue_stats_restart.pl',
      't/020_relallfrozen.pl',
      't/021_heap_page_counters.pl',
      't/022_ao_hidden_tuples.pl',
      't/023_dead_pages.pl',
      't/024_ao_dead_pages.pl',
      't/027_freeze_age_vacuum_count.pl',
      't/028_vacuum_work_core.pl',
    ],
  },
}
